name: spatio-temporal-recon
channels:
- conda-forge
- nvidia/label/cuda-12.4.1
dependencies:
- python>=3.9
- numpy==1.26.4
- scipy
- pip
- matplotlib
- jupyter
- scikit-learn
- scikit-image
- tqdm
- numba
- pywavelets
- cuda-toolkit
- cupy # Comment for no GPU
- nccl # Comment for no GPU
- cudnn # Comment for no GPU
- sympy
